---
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'spike/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
