---
AllCops:
  Exclude:
    - 'spike/*.rb'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
