---

steps:
  - label: ":ruby: 2.5 :rspec:"
    command: "bundle install && bundle exec rspec"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.5"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":ruby: 2.4 :rspec:"
    command: "bundle install && bundle exec rspec"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.4"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":ruby: 2.3 :rspec:"
    command: "bundle install && bundle exec rspec"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.3"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":rubocop:"
    command: "bundle install && bundle exec rubocop"
    plugins:
      docker#v1.2.1:
        image: "ruby"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5
