---

steps:
  - label: ":ruby: 2.6 :rspec:"
    command: ".buildkite/steps/rspec.sh"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.6"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":ruby: 2.5 :rspec:"
    command: ".buildkite/steps/rspec.sh"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.5"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":ruby: 2.4 :rspec:"
    command: ".buildkite/steps/rspec.sh"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.4"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":ruby: 2.3 :rspec:"
    command: ".buildkite/steps/rspec.sh"
    plugins:
      docker#v1.2.1:
        image: "ruby:2.3"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5

  - label: ":rubocop:"
    command: ".buildkite/steps/rubocop.sh"
    plugins:
      docker#v1.2.1:
        image: "ruby"
    agents:
      queue: "platform-docker-spot"
    timeout_in_minutes: 5
